// Code generated by "stringer -type=pemType"; DO NOT EDIT

package security

import "fmt"

const _pemType_name = "CACertificateNodeCertificateClientCertificatePrivateKey"

var _pemType_index = [...]uint8{0, 13, 28, 45, 55}

func (i pemType) String() string {
	i -= 1
	if i >= pemType(len(_pemType_index)-1) {
		return fmt.Sprintf("pemType(%d)", i+1)
	}
	return _pemType_name[_pemType_index[i]:_pemType_index[i+1]]
}
